#!/usr/bin/env python3

import ncplugin
import NCrystal as NC
import numpy as np
import matplotlib.pyplot as plt
import pandas

#physmodel = ncplugin.PhysicsModel( A=66.40901846,  s=1.50279313, rg=14.64271592,  m=4.14778786, p=2.13191984, q1=0.016, sigma0=5.551)
physmodel = ncplugin.PhysicsModel("teshi_xs")

print('cross section @   3.0 Aa : %g barn'%physmodel.calcCrossSection(NC.wl2ekin(3.0)) )
print('cross section @   7.0 Aa : %g barn'%physmodel.calcCrossSection(NC.wl2ekin(7.0)) )
print('cross section @   0.5 eV : %g barn'%physmodel.calcCrossSection( 0.5 ) )
print('cross section @ 0.001 eV : %g barn'%physmodel.calcCrossSection( 0.001 ) )

#wls = np.linspace(0.01,10.0,1000)
#plt.plot( wls, physmodel.calcCrossSection(NC.wl2ekin(wls)) )
#plt.xlabel('angstrom')
#plt.ylabel('barn')
#plt.show()


ekin = np.linspace(0.0001,10.0,1000000)
plt.plot( ekin, physmodel.calcCrossSection(ekin) )
plt.xscale('log')
plt.yscale('log')
plt.xlabel('Energy (eV)')
plt.ylabel('SANS Cross Section (barn)')
plt.xlim(1e-4,1)
plt.ylim(0.01,4000)
plt.grid(which='both', linestyle=':')
plt.show()
