#!/usr/bin/env python3

import ncplugin
import NCrystal as NC
import numpy as np
import matplotlib.pyplot as plt

physmodel = ncplugin.PhysicsModel(A=66.40901846,  s=1.50279313, rg=14.64271592,  m=4.14778786, p=2.13191984, sigma0=5.551)
#physmodel = ncplugin.PhysicsModel(b'teshi_xs')

nsample = int(1e6)#Warning consumes nsample*8 bytes of memory, so don't be silly
                  #and put to 1e10 (if such large numbers are needed, rewrite
                  #code below as loop which samples e.g. 1e6 at a time).

nbins = 180
for wl in np.arange(22,0.5,-7):
    print(f'cross section @  {wl} AA : {physmodel.calcCrossSection( NC.wl2ekin(wl))} barn')
    muvals = physmodel.sampleScatMu( NC.wl2ekin(wl), nvalues=nsample )
    print(f"Average mu in {float(len(muvals)):g}: {muvals.sum()/len(muvals)} with neutron wavelength: {wl}")
    plt.hist(muvals, bins=nbins,alpha=0.5, label=f'wavelength {wl} Å')

#An isotropic distrigbution is constant wrt mu:
#plt.plot( [0.9,1.0],[len(muvals)/nbins]*2 ,label = 'Isotropic', color='red' )

plt.title(r'$\mu=\cos(\theta)$' + f' distribution in {float(len(muvals)):g} scattering events')
plt.legend()
plt.xlabel(r'$\mu=\cos(\theta)$')
plt.yscale('log')
plt.show()
